version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.6
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
