version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:

      - ping 8.8.8.8
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
