version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - yum install rpm-build make gcc glibc -y

  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
