version: 0.2
env:
  variables:

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
