version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws cloudformation package --template-file ./tberror/stage-template.yaml --s3-bucket crosstalk-lambda-artifacts --output-template-file outputSamTemplate.yaml
      
  type: zip
  files:
    - stage-template.yaml
    - outputSamTemplate.yaml
